---
- name: Mount disks and install stuff on the VMs
  hosts: servers
  remote_user: ubuntu
  vars:
    ostack_cloud: lard
    ipalias_network_name: ipalias
    ostack_region: Ostack2-EXT
  pre_tasks:
    - name: List ansible_hosts_all difference from ansible_host (aka the vm not currently being iterated on)
      ansible.builtin.debug:
        msg: "{{ (ansible_play_hosts_all | difference([inventory_hostname])) | first }}"
  roles:
    - role: addsshkeys
    - role: vm_format
      vars:
        name_stuff: "{{ inventory_hostname }}" # name of current vm for finding ipalias port
    - role: ssh
      vars:
        vm_ip: "{{ ansible_host }}" # the current vm's ip

- name: Setup primary and standby
  vars:
    ostack_cloud: lard
    ostack_region: Ostack2-EXT
  hosts: localhost
  gather_facts: false

  roles:
    - role: primarystandbysetup
      vars:
        primary_name: lard-a
        primary_ip: '{{ hostvars[groups["servers"][0]].ansible_host }}' # the first one is a
        standby_name: lard-b
        standby_ip: '{{ hostvars[groups["servers"][1]].ansible_host }}' # the second one is b
